
export write_extxyz
export read_extxyz

import ExtXYZ

"""
    write_extxyz(file::Union{String, IOStream}, atoms::Atoms, R::Matrix, cell::AbstractCell)

Uses ExtXYZ.jl to write a .extxyz file

R can be either a single configuration (Matrix) or many (Vector{<:Matrix}).
"""
function write_extxyz(
    file::Union{String, IOStream}, 
    atoms::Atoms, 
    R::Matrix, 
    cell::AbstractCell
)
    ExtXYZ.write_frame(file, to_extxyz_dict(atoms, R, cell))
end

function write_extxyz(
    file::Union{String, IOStream}, 
    atoms::Atoms, 
    R::Vector{<:Matrix}, 
    cell::AbstractCell
)
    ExtXYZ.write_frames(file, to_extxyz_dict.(Ref(atoms), R, Ref(cell)))
end
function write_extxyz(file::Union{String, IOStream}, structure::Structure)
    ExtXYZ.write_frame(file, structure |> to_extxyz_dict)
end
function write_extxyz(file::Union{String, IOStream}, structure::Vector{Structure})
    ExtXYZ.write_frames(file, structure .|> to_extxyz_dict)
end

"""
    read_extxyz(file::String, index=:)

Use ExtXYZ.jl to read a structure from an ExtXYZ file. 

An `index` can be specified to only read specific structures from the file. 
"""
function read_extxyz(file::Union{String, IOBuffer}, index=:)
    if !isa(index, Colon)
        exyz_structure = ExtXYZ.read_frames(file, index)
    else
        exyz_structure = ExtXYZ.read_frames(file)
    end
    return from_extxyz_dict.(exyz_structure)
end

function to_extxyz_dict(atoms::Atoms, R::Matrix, cell::PeriodicCell; info::Dict{String,Any} = Dict{String,Any}())

    dict = Dict{String, Any}()
    dict["N_atoms"] = length(atoms)

    dict["pbc"] = cell.periodicity

    dict["cell"] = au_to_ang.(permutedims(cell.vectors, (2,1)))

    dict["arrays"] = Dict{String,Any}()
    dict["arrays"]["species"] = String.(atoms.types) |> Array
    dict["arrays"]["pos"] = au_to_ang.(R)

    dict["info"] = info

    return dict
end
to_extxyz_dict(structure::Structure) = to_extxyz_dict(structure.atoms, structure.positions, structure.cell; info = structure.info)

"""
    from_extxyz_dict(dict::Dict{String,Any})

Reads an atomic structure dictionary generated by ExtXYZ.jl and converts it into an NQCBase.Structure. 
"""
function from_extxyz_dict(dict::Dict{String,Any})

    atoms = Atoms(Symbol.(dict["arrays"]["species"]))
    R = ang_to_au.(dict["arrays"]["pos"])
    c = permutedims(dict["cell"], (2,1))
    cell = PeriodicCell{eltype(c)}(ang_to_au.(c), dict["pbc"])

    return Structure(
        atoms, 
        R, 
        cell, 
        dict["info"]
    )
end
